################################################################################
# This file is not native to PDClib and is a part of VisualOS
# Copyright 2020 Scott Maday
# Check the LICENSE file that came with this VisualOS for licensing terms
################################################################################
# This file's working directory is the root of the project

include Make.defaults

all:
		echo "TODO: _dlmalloc!"

include Make.rules